<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'thuan',
                'email' => 'thuan@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0987456123',
                'role' => 1,
                'gender' => 'male',
                'dob' => '2014-11-04',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'thai',
                'email' => 'thai@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0456789123',
                'role' => 1,
                'gender' => 'female',
                'dob' => '2004-11-13',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'hoang',
                'email' => 'hoang@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0123456897',
                'role' => 1,
                'gender' => 'male',
                'dob' => '2004-11-13',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'user4',
                'email' => 'user4@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0900000004',
                'role' => rand(0, 1),
                'gender' => 'male',
                'dob' => '2000-01-01',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'user5',
                'email' => 'user5@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0900000005',
                'role' => rand(0, 1),
                'gender' => 'female',
                'dob' => '2001-02-02',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'user6',
                'email' => 'user6@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0900000006',
                'role' => rand(0, 1),
                'gender' => 'male',
                'dob' => '2002-03-03',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'user7',
                'email' => 'user7@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0900000007',
                'role' => rand(0, 1),
                'gender' => 'female',
                'dob' => '2003-04-04',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'user8',
                'email' => 'user8@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0900000008',
                'role' => rand(0, 1),
                'gender' => 'male',
                'dob' => '2004-05-05',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'user9',
                'email' => 'user9@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0900000009',
                'role' => rand(0, 1),
                'gender' => 'female',
                'dob' => '2005-06-06',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'user10',
                'email' => 'user10@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0900000010',
                'role' => rand(0, 1),
                'gender' => 'male',
                'dob' => '2006-07-07',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'user11',
                'email' => 'user11@gmail.com',
                'password' => Hash::make('1234'),
                'phone' => '0900000011',
                'role' => rand(0, 1),
                'gender' => 'female',
                'dob' => '2007-08-08',
                'is_active' => 1,
                'profile_image' => 'uploads/team-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
